services:
  - type: web
    name: lab-report-analyzer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    buildFilter:
      paths:
        - apt-packages.txt
